name: Bug Report
description: Create a new ticket for a bug.

labels:
  - "bug"
assignees:
  - Strappazzon

body:
  - type: markdown
    attributes:
      value: Read the [Contributing Guidelines](https://github.com/Strappazzon/mkdocs-material-midnight/blob/-/.github/CONTRIBUTING.md) before opening a ticket.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a description of the issue.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Provide a screenshot showing the issue.
    validations:
      required: false

  - type: input
    id: mkdocs-material
    attributes:
      label: Material for MkDocs Version
      description: The version of Material for MkDocs you are using.
      placeholder: "9.6.3"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser Version
      description: The browser and version that you are using.
      placeholder: Firefox 118.0.2
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: The operating system you are using.
      placeholder: Debian 11
    validations:
      required: false

  - type: textarea
    id: fix
    attributes:
      label: Proposed Fix
      description: Explain how you think this should be fixed.
    validations:
      required: false

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to the [Code of Conduct](https://github.com/Strappazzon/.github/blob/-/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the Code of Conduct.
          required: true
