name: Documentation Change
description: Request an update to the documentation.

labels:
  - "documentation"

assignees:
  - Strappazzon

body:
  - type: markdown
    attributes:
      value: Read the [Contributing Guidelines](https://github.com/Strappazzon/mkdocs-material-midnight/blob/-/.github/CONTRIBUTING.md) before opening a ticket.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What can be clarified or further explained.
    validations:
      required: true

  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to the [Code of Conduct](https://github.com/Strappazzon/.github/blob/-/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the Code of Conduct.
          required: true
